version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: test-gatling
    container_name: test-gatling
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
      - ./:/app